### ISSUE TITLE
error in class   DoGetCert.cs    SslFlags.Sni  not Exist 

### ISSUE THREAD

**Issue by ankitchourasia07** [GeorgeSchiro/GetCert#1]
show error not Exist  SslFlags.Sni 
 private void OsSpecificBinding(Site aoSite, X509Store aoStore, X509Certificate2 aoCertificate, string asBindingInformation)
        {
            aoSite.Bindings.Add(asBindingInformation, aoCertificate.GetCertHash(), aoStore.Name, SslFlags.Sni);
        }

**Comment by GeorgeSchiro** [comment]
Any lack of SNI support should have been trapped in "bGetCertificate()".

Was it an uncaught exception? Or did it appear in the log? Please be more specific.

**Comment by GeorgeSchiro** [comment]
Double checked. We do test in Win2008 R2 as well as more recent versions. I verified there are no issues running the get certificate process to completion, including installing new certificates and binding them.

Perhaps you are using an older version of Windows Server? Please note the minimum hardware requirements:

[GetCert Requirements](https://github.com/GeorgeSchiro/GetCert#Requirements)

**Comment by GeorgeSchiro** [comment]
I just realized what you meant.  Here's the actual error (I'm guessing):

    The name 'SslFlags' does not exist in the current context

This is a compile-time error that occurs on OS versions that don't support SNI. SNI started with Win2012 (ie. IIS 8). You need to compile the code on a Win20012 machine (or newer). That said, the software will still run on Win2008 R2 (without SNI support).

**Comment by GeorgeSchiro** [comment]
Thank you for bringing this to my attention. I apologize for not taking it seriously sooner.
